// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqyvqjvewkqgxzxdaifm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xeXZxanZld2txZ3h6eGRhaWZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5OTk0NjIsImV4cCI6MjA3MTU3NTQ2Mn0.bHEHQvxQpoRS2S6SZkpsElr6Uw0xANqfjNxQbCF1Kdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});